services:
  dashboard:
    container_name: dashboard
    image: ghcr.io/runcitadel/dashboard:citadel-0.0.10@sha256:88ed2002be886d3fa053cde0573d2f4239f893e307572841ea0ba7dd8b8534d3
    restart: on-failure
    stop_grace_period: 15s
    networks:
      default:
        ipv4_address: $DASHBOARD_IP
  api:
    container_name: api
    image: runcitadel/api:main@sha256:26afc1bc1ef91a22a1789e5d960f04b2aa6f9d488c25ee4cb364c0ccaa3bd186
    restart: on-failure
    init: true
    stop_grace_period: 30s
    volumes:
    - ${PWD}/info.json:/info.json
    - ${PWD}/db:/db
    - ${PWD}/karen.socket:/karen.socket
    - ${PWD}/apps:/apps
    - ${PWD}/statuses:/statuses
    - jwt-public-key:/jwt-public-key
    - jwt-private-key:/jwt-private-key
    environment:
      USER_PASSWORD_FILE: /db/user.json
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      JWT_PRIVATE_KEY_FILE: /jwt-private-key/jwt.key
      JWT_EXPIRATION: '3600'
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://nirvati.local"}
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-""}
      SEED_FILE: /db/nirvati-seed/seed
      GITHUB_REPO: nirvati/nirvati-core
      GITHUB_BRANCH: ${UPDATE_CHANNEL:-"stable"}
      VERSION_FILE: /info.json
      UPDATE_LOCK_FILE: /statuses/update-in-progress
      BACKUP_STATUS_FILE: /statuses/backup-status.json
      DEBUG_STATUS_FILE: /statuses/debug-status.json
      IS_NIRVATI_OS: ${IS_NIRVATI_OS:-"true"}
      KAREN_SOCKET: /karen.socket
      IP_ADDR: $DEVICE_IP
    networks:
      default:
        ipv4_address: $API_IP
  postgres:
    container_name: postgres
    image: postgres:15.1@sha256:02547253a07e6edd0c070caba1d2a019b7dc7df98b948dc9a909e1808eb77024
    restart: on-failure
    init: true
    stop_grace_period: 2m
    volumes:
    - ${PWD}/postgres:/db
    environment:
      USER_PASSWORD_FILE: /db/user.json
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      JWT_PRIVATE_KEY_FILE: /jwt-private-key/jwt.key
      JWT_EXPIRATION: '3600'
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://nirvati.local"}
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-""}
      SEED_FILE: /db/nirvati-seed/seed
      GITHUB_REPO: nirvati/nirvati-core
      GITHUB_BRANCH: ${UPDATE_CHANNEL:-"stable"}
      VERSION_FILE: /info.json
      UPDATE_LOCK_FILE: /statuses/update-in-progress
      BACKUP_STATUS_FILE: /statuses/backup-status.json
      DEBUG_STATUS_FILE: /statuses/debug-status.json
      IS_NIRVATI_OS: ${IS_NIRVATI_OS:-"true"}
      KAREN_SOCKET: /karen.socket
      IP_ADDR: $DEVICE_IP
    networks:
      default:
        ipv4_address: $API_IP
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
networks:
  default:
    name: nirvati_main_network
    ipam:
      driver: default
      config:
      - subnet: $NETWORK_IP/24
volumes:
  jwt-public-key:
    name: citadel-jwt-public-key
  jwt-private-key:
    name: citadel-jwt-private-key
