#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 Umbrel https://getumbrel.com
# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors
# SPDX-FileCopyrightText: 2023 Nirvati and contributors
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

# Start Nirvati

if [[ $UID != 0 ]]; then
    echo "Nirvati must be started as root"
    echo "Please re-run this script as"
    echo "  sudo ./scripts/start"
    exit 1
fi

check_dependencies () {
  for cmd in "$@"; do
    if ! command -v $cmd >/dev/null 2>&1; then
      echo "Nirvati requires \"${cmd}\" to be installed."
      exit 1
    fi
  done
}

# Check system's dependencies
check_dependencies readlink dirname ip docker

# Check OTA update scripts' dependencies
check_dependencies rsync jq curl

NIRVATI_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/.."
NIRVATI_LOGS="${NIRVATI_ROOT}/logs"

# Configure Nirvati if it isn't already configured
if [[ ! -f "${NIRVATI_ROOT}/statuses/configured" ]]; then
  CADDY_PORT=${CADDY_PORT:-80} CADDY_HTTPS_PORT=${CADDY_HTTPS_PORT:-443} "${NIRVATI_ROOT}/scripts/configure"
fi

echo
echo "======================================"
echo "============= STARTING ==============="
echo "============= NIRVATI ================"
echo "======================================"
echo

echo "Setting environment variables..."
echo

# Check Nirvati OS
[[ -f "/etc/default/nirvati" ]] && source "/etc/default/nirvati"
if [[ -z "${NIRVATI_OS:-}" ]]; then
  export IS_NIRVATI_OS="false"
else
  export IS_NIRVATI_OS="true"
fi

# Whitelist device IP and hostname for CORS
DEVICE_IP=$(hostname -I | awk '{print $1}') || DEVICE_IP="$(ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | head -n 1 | awk '/inet/ {print $2}' | cut -d'/' -f1)"
DEVICE_HOSTNAME="$(hostname)" || DEVICE_HOSTNAME="$(cat /etc/hostname)"
DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.local,https://${DEVICE_HOSTNAME}.local,http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAME}"
export DEVICE_HOSTS=$DEVICE_HOSTS
export DEVICE_HOSTNAME="${DEVICE_HOSTNAME}.local"
export DEVICE_IP=$DEVICE_IP

cd "$NIRVATI_ROOT"

echo "Starting karen..."
echo
./karen &>> "${NIRVATI_LOGS}/karen.log" &

echo "Starting status monitors..."
echo
pkill -f ./scripts/status-monitor || true
./scripts/status-monitor memory 300 &>> "${NIRVATI_LOGS}/status-monitor.log" &
./scripts/status-monitor storage 60 &>> "${NIRVATI_LOGS}/status-monitor.log" &
./scripts/status-monitor temperature 15 &>> "${NIRVATI_LOGS}/status-monitor.log" &
./scripts/status-monitor uptime 15 &>> "${NIRVATI_LOGS}/status-monitor.log" &
./scripts/status-monitor app-updates 1800 &>> "${NIRVATI_LOGS}/status-monitor.log" &

echo "Starting backup monitor..."
echo
./scripts/backup/monitor &>> "${NIRVATI_LOGS}/backup-monitor.log" &

echo "Starting decoy backup trigger..."
echo
./scripts/backup/decoy-trigger &>> "${NIRVATI_LOGS}/backup-decoy-trigger.log" &

echo "Resetting config files"
echo
./scripts/configure

echo
echo "Starting Docker services..."
echo
docker compose up --detach --build --remove-orphans || {
  echo "Failed to start containers"
  exit 1
}
echo

# Unlock the user file on each start of Nirvati to avoid issues
# Normally, the user file shouldn't ever be locked, if it is, something went wrong, but it could still be working
if [[ -f "${NIRVATI_ROOT}/db/user.json.lock" ]]; then
  echo "WARNING: The user file was locked, Nirvati probably wasn't shut down properly"
  rm "${NIRVATI_ROOT}/db/user.json.lock"
fi

echo
echo "Starting installed apps..."
echo
./scripts/app start installed
echo

echo "Nirvati is now accessible at"
echo "  http://${DEVICE_HOSTNAME}"
echo "  http://${DEVICE_IP}"
